# Generated by Django 3.2 on 2023-03-16 14:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, help_text='Введите slug-идентификатор', unique=True, verbose_name='Слаг-индентификатор'),
        ),
    ]
