# Generated by Django 3.2 on 2023-03-21 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_title_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'default_related_name': 'titles', 'verbose_name': 'Произведение', 'verbose_name_plural': 'Произведения'},
        ),
    ]
