# Generated by Django 3.2 on 2023-03-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_categories_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.SlugField(help_text='Введите slug-идентификатор', unique=True, verbose_name='Слаг-индентификатор'),
        ),
    ]
