# Generated by Django 3.2 on 2023-03-18 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_review_title'),
        ('reviews', '0005_auto_20230317_1747'),
    ]

    operations = [
    ]
