# Generated by Django 3.2 on 2023-03-18 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_merge_0004_alter_review_title_0005_auto_20230317_1747'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Genres',
            new_name='Genre',
        ),
        migrations.RenameModel(
            old_name='Titles',
            new_name='Title',
        ),
    ]
